# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

group_sums <- function(kv, kT) {
    .Call(`_bife_group_sums`, kv, kT)
}

group_sums_bias <- function(kM, kw, kT) {
    .Call(`_bife_group_sums_bias`, kM, kw, kT)
}

group_sums_cov <- function(kM1, kM2, kT) {
    .Call(`_bife_group_sums_cov`, kM1, kM2, kT)
}

group_sums_spectral <- function(kM, kv, kw, kL, kT) {
    .Call(`_bife_group_sums_spectral`, kM, kv, kw, kL, kT)
}

group_sums_var <- function(kM, kT) {
    .Call(`_bife_group_sums_var`, kM, kT)
}

center_variables <- function(kM, kw, kT) {
    .Call(`_bife_center_variables`, kM, kw, kT)
}

update_alpha <- function(ku, kw, kT) {
    .Call(`_bife_update_alpha`, ku, kw, kT)
}

variance_alpha <- function(kV, kX, kw, kT) {
    .Call(`_bife_variance_alpha`, kV, kX, kw, kT)
}

